import { t } from "i18next";
export const referenceData = [
	{
		id: 1,
		title: "Am Tacheles",
		year: "2022",
		city: "Berlin",
		slug: "am-tacheles",
		category: "Občianska výstavba",
		img: "/AM-Tacheles/AM-Tacheles-1.jpg",
		images: [
			"/AM-Tacheles/AM-Tacheles-1.jpg",
			"/AM-Tacheles/AM-Tacheles-2.jpg",
			"/AM-Tacheles/AM-Tacheles-3.jpg",
			"/AM-Tacheles/AM-Tacheles-4.jpg",
			"/AM-Tacheles/AM-Tacheles-5.jpg",
			"/AM-Tacheles/AM-Tacheles-6.jpg",
		],
	},
	{
		id: 2,
		title: "Mercator One",
		year: "2016",
		city: "Duisburg",
		slug: "mercator-one",
		category: "Občianska výstavba",
		img: "/Mercator One/Mercator One 1.jpg",
		images: [
			"/Mercator One/Mercator One 1.jpg",
			"/Mercator One/Mercator One 2.jpg",
			"/Mercator One/Mercator One 3.jpg",
		],
	},
	{
		id: 3,
		title: "Hotel H2",
		year: "2016",
		city: "Leipzig",
		slug: "hotel-h2",
		category: "Občianska výstavba",
		img: "/Hotel H2 Hyperion/Hotel H2 Hyperion 1.jpg",
		images: [
			"/Hotel H2 Hyperion/Hotel H2 Hyperion 1.jpg",
			"/Hotel H2 Hyperion/Hotel H2 Hyperion 2.jpg",
			"/Hotel H2 Hyperion/Hotel H2 Hyperion 3.jpg",
			"/Hotel H2 Hyperion/Hotel H2 Hyperion 4.jpg",
			"/Hotel H2 Hyperion/Hotel H2 Hyperion 5.jpg",
		],
	},
	{
		id: 4,
		title: "AW Institut",
		year: "2018",
		city: "Rostrock",
		slug: "institut-alfred-wegener",
		category: "Občianska výstavba",
		img: "/Alfred Wegener Institute/Alfred Wegener Institute 1.jpg",
		images: [
			"/Alfred Wegener Institute/Alfred Wegener Institute 1.jpg",
			"/Alfred Wegener Institute/Alfred Wegener Institute 2.jpg",
			"/Alfred Wegener Institute/Alfred Wegener Institute 3.jpg",
		],
	},
	{
		id: 5,
		title: "Labor Wisplinghoff",
		year: "2022",
		city: "Leipzig",
		slug: "labor-wisplinghoff",
		category: "Občianska výstavba",
		img: "/Labor Wisplinghoff/Labor Wisplinghoff 1.jpg",
		images: [
			"/Labor Wisplinghoff/Labor Wisplinghoff 1.jpg",
			"/Labor Wisplinghoff/Labor Wisplinghoff 2.jpg",
			"/Labor Wisplinghoff/Labor Wisplinghoff 3.jpg",
			"/Labor Wisplinghoff/Labor Wisplinghoff 4.jpg",
		],
	},
	{
		id: 6,
		title: "Mannheim Turley Barracks",
		year: "2021",
		city: "Köln",
		slug: "mannheim-turley-barracks",
		category: "Občianska výstavba",
		img: "/Mannheim Turley Barracks/Mannheim Turley Barracks 2.jpg",
		images: [
			"/Mannheim Turley Barracks/Mannheim Turley Barracks 1.jpg",
			"/Mannheim Turley Barracks/Mannheim Turley Barracks 2.jpg",
			"/Mannheim Turley Barracks/Mannheim Turley Barracks 3.jpg",
		],
	},
	{
		id: 7,
		title: "Neue Mitte Altona",
		year: "2018",
		city: "Potsdam",
		slug: "awi-institut",
		category: "Občianska výstavba",
		img: "/Neue Mitte Altona/Neue Mitte Altona 1.jpg",
		images: [
			"/Neue Mitte Altona/Neue Mitte Altona 1.jpg",
			"/Neue Mitte Altona/Neue Mitte Altona 2.jpg",
			"/Neue Mitte Altona/Neue Mitte Altona 3.jpg",
			"/Neue Mitte Altona/Neue Mitte Altona 4.jpg",
		],
	},
	{
		id: 8,
		title: "VGP Komplex",
		year: "2020",
		city: "Berlin",
		slug: "vgp-komplex",
		category: "Občianska výstavba",
		img: "/Berlin VGP Komplex/Berlin VGP Komplex 1.jpg",
		images: [
			"/Berlin VGP Komplex/Berlin VGP Komplex 1.jpg",
			"/Berlin VGP Komplex/Berlin VGP Komplex 2.jpg",
			"/Berlin VGP Komplex/Berlin VGP Komplex 3.jpg",
			"/Berlin VGP Komplex/Berlin VGP Komplex 4.jpg",
		],
	},
	{
		id: 9,
		title: "Reinbek Schulzentrum",
		year: "2020",
		city: "Berlin",
		slug: "reinbek",
		category: "Občianska výstavba",
		img: "/Schulzentrum Reinbek/Schulzentrum Reinbek 1.jpg",
		images: [
			"/Schulzentrum Reinbek/Schulzentrum Reinbek 1.jpg",
			"/Schulzentrum Reinbek/Schulzentrum Reinbek 2.jpg",
			"/Schulzentrum Reinbek/Schulzentrum Reinbek 3.jpg",
			"/Schulzentrum Reinbek/Schulzentrum Reinbek 4.jpg",
			"/Schulzentrum Reinbek/Schulzentrum Reinbek 5.jpg",
		],
	},
	{
		id: 10,
		title: "Technologiekreis Adlershof",
		year: "2020",
		city: "Berlin",
		slug: "technologiekreis-adlershof",
		category: "Občianska výstavba",
		img: "/Technologiekreis Adlershof/Technologiekreis Adlershof 1.jpg",
		images: [
			"/Technologiekreis Adlershof/Technologiekreis Adlershof 1.jpg",
			"/Technologiekreis Adlershof/Technologiekreis Adlershof 2.jpg",
			"/Technologiekreis Adlershof/Technologiekreis Adlershof 3.jpg",
		],
	},
	{
		id: 11,
		title: "UKSH Universitatsklinikum",
		year: "2020",
		city: "Berlin",
		slug: "uksh-universitatsklinikum",
		category: "Občianska výstavba",
		img: "/UKSH Universitatsklinikum Schleswig-Holstein/UKSH Universitatsklinikum Schleswig-Holstein 1.jpg",
		images: [
			"/UKSH Universitatsklinikum Schleswig-Holstein/UKSH Universitatsklinikum Schleswig-Holstein 1.jpg",
			"/UKSH Universitatsklinikum Schleswig-Holstein/UKSH Universitatsklinikum Schleswig-Holstein 2.jpg",
		],
	},
	{
		id: 12,
		title: "Universitat Siegen",
		year: "2020",
		city: "Berlin",
		slug: "universitat-siegen",
		category: "Občianska výstavba",
		img: "/Universitat Siegen/Universitat Siegen 1.jpg",
		images: [
			"/Universitat Siegen/Universitat Siegen 1.jpg",
			"/Universitat Siegen/Universitat Siegen 2.jpg",
			"/Universitat Siegen/Universitat Siegen 3.jpg",
			"/Universitat Siegen/Universitat Siegen 4.jpg",
			"/Universitat Siegen/Universitat Siegen 5.jpg",
		],
	},
	{
		id: 13,
		title: "Wuppertaler Hauptbahnhof",
		year: "2020",
		city: "Berlin",
		slug: "wuppertaler-hauptbahnhof",
		category: "Občianska výstavba",
		img: "/Wuppertaler Hauptbahnhof/Wuppertaler Hauptbahnhof 1.jpg",
		images: [
			"/Wuppertaler Hauptbahnhof/Wuppertaler Hauptbahnhof 1.jpg",
			"/Wuppertaler Hauptbahnhof/Wuppertaler Hauptbahnhof 2.jpg",
			"/Wuppertaler Hauptbahnhof/Wuppertaler Hauptbahnhof 3.jpg",
		],
	},
];
